"""empty message

Revision ID: 0bd9a19d5fa8
Revises: 275952f26f45
Create Date: 2025-05-23 22:59:28.022527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bd9a19d5fa8'
down_revision: Union[str, None] = '275952f26f45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crew_role', sa.Column('test', sa.String(length=1000), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('crew_role', 'test')
    # ### end Alembic commands ###
